### PR TITLE
add a cli for HakuIR

### PR DESCRIPTION
**Pull request by ntrwansuiBC**
change the project structure let the repo can work as a cli

### **follow commands:** 
image
**models** List avaliable models(has toml and pth)
**upscale** Just upscale
**restoration** Just restoration
**upscale-before-ir** Upscale before restoration
**upscale-after-ir** Upscale after restoration
image

### CODE REVIEW

**Comment by KohakuBlueleaf** [comment]
@ntrwansuiBC Thx for your contribution!!
But may I ask you to change the naming to fit PEP8 ?

**Comment by KohakuBlueleaf** [comment]
Can you convert the small camal case in cli.py to xxx_yyy naming?

**Comment by ntrwansuiBC** [comment]
I renamed all 'cli' to 'console',if use the full name of 'cli',‘command_line_interface’,some function name will be very very long

**Comment by KohakuBlueleaf** [comment]
> I renamed all 'cli' to 'console',if use the full name of 'cli',‘command_line_interface’,some function name will be very very long

Short term doesn't matter at all, small camal case is the only problem in here

**Comment by KohakuBlueleaf** [comment]
(correction: short term that basically everyone know what it is doesn't matter)

**Comment by ntrwansuiBC** [comment]
好，所有形如xxxCommand的变量都已经改成xxx_command了
需要我把文件名和模块名改回去吗

**Comment by KohakuBlueleaf** [comment]
@ntrwansuiBC 可以改回去

**Comment by KohakuBlueleaf** [comment]
LGTM now

**Pull request merged**
